#include "BoostExceptionHandler.h"

void boost::throw_exception(std::exception const & e)
{
	
}
